import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Features from '@/components/Features'
import Navbar from '@/components/Navbar'
import Testimonal from '@/components/Testimonials'
import Pricing from '@/components/Pricing'
import Hero from '@/components/Hero'
import Footer from '@/components/Footer'
import Sponsors from '@/components/Sponsors'
import { Container } from '@chakra-ui/react'
import Layout from '@/components/Layout'
import About from '@/components/About'
const inter = Inter({ subsets: ['latin'] })

export default function Trade() {
  return (
    <>
      <Head>
        <title>FM Capital</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <>
        <Layout>
        <About/>
        </Layout>
      </>
    </>
  )
}
